name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Build the project
      env:
        API_KEY: ${{ secrets.API_KEY }}
        AUTH_DOMAIN: ${{ secrets.AUTH_DOMAIN }}
        PROJECT_ID: ${{ secrets.PROJECT_ID }}
        STORAGE_BUCKET: ${{ secrets.STORAGE_BUCKET }}
        MESSAGING_SENDER_ID: ${{ secrets.MESSAGING_SENDER_ID }}
        APP_ID: ${{ secrets.APP_ID }}
        MEASUREMENT_ID: ${{ secrets.MEASUREMENT_ID }}
      run: |
        # Replace the placeholders in your code with the actual secrets
        sed -i 's|API_KEY|'"$API_KEY"'|g' index.html
        sed -i 's|AUTH_DOMAIN|'"$AUTH_DOMAIN"'|g' index.html
        sed -i 's|PROJECT_ID|'"$PROJECT_ID"'|g' index.html
        sed -i 's|STORAGE_BUCKET|'"$STORAGE_BUCKET"'|g' index.html
        sed -i 's|MESSAGING_SENDER_ID|'"$MESSAGING_SENDER_ID"'|g' index.html
        sed -i 's|APP_ID|'"$APP_ID"'|g' index.html
        sed -i 's|MEASUREMENT_ID|'"$MEASUREMENT_ID"'|g' index.html
